config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "landing#home"
  resources :users, only: %i(show edit update)
  resources :credit_cards, except: [:show]
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  attr_encrypted :card_number, key: Rails.application.credentials.key
  attr_encrypted :cvv, key: Rails.application.credentials.key

  include Askable

  # ASSOCIATIONS
  # --------------------------------

  belongs_to :wallet
  delegate :user, to: :wallet, allow_nil: true

  # VALIDATIONS
  # --------------------------------

  def self.brands
    %w(visa mastercard american_express)
  end
  
  validates :year,  presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 9999 } 
  validates :month, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 12 } 
  validates :brand, presence: true, inclusion: { in: CreditCard.brands, message: "is not supported" }
  validates :cvv, presence: true, numericality: { only_integer: true }, length: { maximum: 3, minimum: 3 }
  validates :card_number, presence: true, uniqueness: true
  validates_format_of :card_number, with: visa_regex, if: :visa?
  validates_format_of :card_number, with: mastercard_regex, if: :mastercard?
  validates_format_of :card_number, with: amex_regex, if: :american_express?

  # BOOLEANS
  # --------------------------------

  set_askers %i(visa mastercard american_express)

  def has_funds?(amount)
    true
  end
end

app/controllers/API/V1/credit_cards_controller.rb
module API
  module V1
    class CreditCardsController < ApplicationController
    end
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  load_and_authorize_resource
  
  respond_to    :html, :json
  before_action :find_current_credit_card, only: %i(edit update destroy)
  
  include CreditCardsHelper

  def index
    @credit_cards = current_user.credit_cards
  end

  def new
    @credit_card = credit_cards.new
  end

  def edit
  end

  def create
    @credit_card = credit_cards.new(card_attrs)
    if @credit_card.save
      respond_with(@credit_card, location: credit_cards_path)
    else
      respond_with(@credit_card, status: :bad_request)
    end
  end

  def update
    if @credit_card.update_attributes(card_attrs)
      respond_with(@credit_card, location: credit_cards_path)
    else
      respond_with(@credit_card, status: :bad_request)
    end
  end

  def destroy
    @credit_card.destroy
    respond_with(@credit_card, location: credit_cards_path)
  end

  private

  delegate :wallet, to: :current_user
  delegate :credit_cards, to: :wallet

  def find_current_credit_card
    @credit_card = credit_cards.find(params[:id])
  end
end

app/helpers/api/credit_cards_helper.rb
module Api::CreditCardsHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
  def card_attrs
    params.require(:credit_card).permit %i(card_number brand year month cvv)
  end

  alias_method :update_params, :card_attrs
  alias_method :create_params, :card_attrs
end

app/views/credit_cards/_credit_card_summary.html.erb
<% cache credit_card do %>
<tr id="<%= credit_card.id %>">
  <td>
    <%= credit_card.card_number %>
  </td>
  <td>
    <%= "#{credit_card.month}/#{credit_card.year}" %>
  </td>
  <td>
    <%= credit_card.brand %>
  </td>
  <td>
    <%= link_to("Edit", edit_credit_card_path(credit_card)) %>
    /
    <%= link_to 'Delete',  credit_card,  method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>
<% end %>

app/views/credit_cards/_form.html.erb
<%= form_for @credit_card, url: path, method: url_method do |f| %>
<p>
  Card Numer: <%= f.number_field :card_number %>
  <br>
  <%= @credit_card.errors[:card_number].join(', ')  unless @credit_card.errors.empty? %> 
</p>

<p>
  Year: <%= f.number_field :year %>
  <br>
  <%= @credit_card.errors[:year].join(', ')  unless @credit_card.errors.empty? %> 
</p>

<p>
  Month: <%= f.number_field :month %>
  <br>
  <%= @credit_card.errors[:month].join(', ')  unless @credit_card.errors.empty? %> 
</p>

<p>
  CVV: <%= f.number_field :cvv %>
  <br>
  <%= @credit_card.errors[:cvv].join(', ')  unless @credit_card.errors.empty? %> 
</p>

<p>
  brand: <%= f.select(:brand, %w(american_express mastercard visa), {}) %>
  <%= @credit_card.errors[:brand].join(', ')  unless @credit_card.errors.empty? %>
</p>
  <%= f.submit %>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>CreditCards#edit</h1>
<%= render partial: 'form', locals: { path: credit_card_path(@credit_card), url_method: :put } %>

app/views/credit_cards/index.html.erb
<h1>CreditCards#index</h1>
<%= link_to("Add credit card", new_credit_card_path) %>
<table id="credit_cards">
  <thead>
    <tr>
      <th>Card Number</th>
      <th>Expiration Date</th>
      <th>Brand</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% cache ["credit_cards", @credit_cards.map(&:id), (@credit_cards.maximum(:updated_at).strftime('%Y%m%d%H%M%S%6N'))] do %>
      <%= render partial: "credit_card_summary", collection: @credit_cards, as: :credit_card %>
    <% end %>
  </tbody>
</table>

app/views/credit_cards/new.html.erb
<h1>CreditCards#new</h1>
<%= render partial: 'form', locals: { path: credit_cards_path, url_method: :post } %>